version: "3.9"
services:
  postgres:
    container_name: nto-postgres
    image: nto-postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "${NTO_POSTGRES_USER_PASSWORD:?err}"
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${NTO_POSTGRES_HOST_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - proxynet

  pgadmin:
    container_name: nto-pgadmin
    image: dpage/pgadmin4:6
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "${NTO_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${NTO_PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "${NTO_PGADMIN_HOST_PORT}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - proxynet

networks:
  proxynet:
    name: postgres
