version: "3.9"
services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    # command:
    #   - "postgres"
      # - "-c"
      # - "max_connections=50"
      # - "-c"
      # - "shared_buffers=1GB"
      # - "-c"
      # - "effective_cache_size=4GB"
      # - "-c"
      # - "work_mem=16MB"
      # - "-c"
      # - "maintenance_work_mem=512MB"
      # - "-c"
      # - "random_page_cost=1.1"
      # - "-c"
      # - "temp_file_limit=10GB"
      # - "-c"
      # - "log_min_duration_statement=200ms"
      # - "-c"
      # - "idle_in_transaction_session_timeout=10s"
      # - "-c"
      # - "lock_timeout=1s"
      # - "-c"
      # - "statement_timeout=60s"
      # - "-c"
      # - "shared_preload_libraries=pg_stat_statements"
      # - "-c"
      # - "pg_stat_statements.max=10000"
      # - "-c"
      # - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:?err}"
      POSTGRES_USER: "${POSTGRES_USER:?err}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?err}"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER:?err} -d ${POSTGRES_DB:?err}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:${PGADMIN_TAG}
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
